name: Build Astera
on: push

jobs:
  build:
    name: Build Astera
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]
        #cxx: [g++, g++-8, g++-9, clang++, clang++-8, clang++-9]
        #cc: [gcc, gcc-8, gcc-9, clang, clang-8, clang-9]
    env:
      CMAKE_GENERATOR: Ninja
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install CMake and Ninja
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade cmake ninja
      - name: Install Apt Dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y mesa-common-dev xorg-dev libgl-dev
      - name: Configure
        run: cmake -Bbuild -S${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DASTERA_BUILD_DOCS=ON
      - name: Build
        run: cmake --build build
