name: Build [Docs]

on: 
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build  
        run: sudo apt-get update -qq
      - name: Install Dependencies
        run: sudo apt-get install -y --no-install-recommends mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
      - name: Generate CMake Build
        run: cmake -S. -Bbuild
      - name: Run CMake Build
        run: cmake --build build
