name: Build Documentation
on: push

jobs:
  build:
    name: Build Documents
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Sphinx Theme
        uses: actions/checkout@v2
        with:
          repository: readthedocs/sphinx_rtd_theme
          path: docs/_themes/
      - name: Sphinx Build
        uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: "docs/"
          build-command: "make html"
      - name: Create artifact
        uses: actions/upload-artifact@v1
        with:
          name: Documentation (HTML)
          path: docs/_build/html/
      - name: Get GH-Pages Branch
        uses: actions/checkout@v2
        with:
          repository: tek256/astera
          token: ${{ github.token }}
          path: gh-pages
          ref: gh-pages
      - name: Commit changes
        run: |
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub"
          git add .
          git commit -m "Updated documentation" 
          cd ..
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
