name: Build All [OSX]

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Everything
        run: ./build_unix.sh -a
