name: Build All [OSX]

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Generate CMake Build
        run: cmake -Bbuild -G "Unix Makefiles" -S.
      - name: Run CMake Build
        run: cmake --build build

