name: C Build Check (Windows)

on: 
  milestone:
	types: [opened, deleted]

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    - name: build openal-soft
      run: |
          cd dep/openal-soft
          cmake -G "MSYS Makefiles"
          make
          make install
          cd ../../
    - name: build glfw
      run: |
          cd dep/glfw/
          cmake -G "MSYS Makefiles"
          make
          make install
          cd ../../
    - name: build zip
      run: |
          cd dep/zip/
          cmake -G "MSYS Makefiles"
          make
          make install
          cd ../../
    - name: build engine
      run: make CC=gcc

